import { NextResponse } from "next/server";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export async function POST(req) {
  try {
    const body = await req.json();
    const { lang = "it", currencySymbol = "€", inputs, outputs, meta } = body || {};

    if (!inputs || !outputs) {
      return NextResponse.json({ error: "Missing inputs/outputs" }, { status: 400 });
    }

    const t =
      lang === "it"
        ? {
            title: "Real Ecommerce Profit — Report",
            subtitle: "Stima operativa (non consulenza fiscale/finanziaria).",
            sectionKpi: "Risultati principali",
            sectionInputs: "Assunzioni (input)",
            sectionNotes: "Interpretazione",
            profit: "Profitto netto per ordine",
            margin: "Margine netto",
            beAds: "Spesa ads massima per non andare in perdita",
            beReturn: "Rendimento ads minimo per non andare in perdita",
            generated: "Generato da realecommerceprofit.com",
          }
        : {
            title: "Real Ecommerce Profit — Report",
            subtitle: "Operational estimate (not financial/tax advice).",
            sectionKpi: "Key results",
            sectionInputs: "Assumptions (inputs)",
            sectionNotes: "Insight",
            profit: "Net profit per order",
            margin: "Net margin",
            beAds: "Max ad spend to avoid losing money",
            beReturn: "Min ad return to avoid losing money",
            generated: "Generated by realecommerceprofit.com",
          };

    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([595.28, 841.89]); // A4 portrait
    const { width, height } = page.getSize();

    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const marginX = 44;
    let y = height - 56;

    const colorText = rgb(0.12, 0.14, 0.17);
    const colorMuted = rgb(0.45, 0.48, 0.52);
    const colorLine = rgb(0.88, 0.90, 0.92);
    const colorAccent = rgb(0.19, 0.45, 0.96);

    const drawText = (text, x, y, size = 12, bold = false, color = colorText) => {
      page.drawText(String(text ?? ""), {
        x,
        y,
        size,
        font: bold ? fontBold : font,
        color,
      });
    };

    const drawLine = (y) => {
      page.drawLine({
        start: { x: marginX, y },
        end: { x: width - marginX, y },
        thickness: 1,
        color: colorLine,
      });
    };

    const money = (n) => {
      const v = Number(n || 0);
      const sign = v < 0 ? "-" : "";
      const abs = Math.abs(v);
      const str = abs.toFixed(2);
      const parts = str.split(".");
      const int = parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, ",");
      const dec = parts[1];
      return `${sign}${currencySymbol}${int}.${dec}`;
    };

    const pct = (n) => `${(Number(n || 0) * 100).toFixed(1)}%`;

    // Header
    drawText(t.title, marginX, y, 18, true);
    y -= 22;
    drawText(t.subtitle, marginX, y, 10, false, colorMuted);

    // small meta
    const now = new Date();
    const stamp = now.toISOString().slice(0, 19).replace("T", " ");
    y -= 16;
    drawText(`${t.generated} • ${stamp}`, marginX, y, 9, false, colorMuted);

    y -= 18;
    drawLine(y);
    y -= 22;

    // KPI section
    drawText(t.sectionKpi, marginX, y, 13, true);
    y -= 14;

    const boxH = 70;
    const gap = 12;
    const boxW = (width - marginX * 2 - gap) / 2;

    const drawKpiBox = (x, yTop, title, value) => {
      page.drawRectangle({
        x,
        y: yTop - boxH,
        width: boxW,
        height: boxH,
        borderColor: colorLine,
        borderWidth: 1,
        color: rgb(0.97, 0.98, 0.99),
      });
      drawText(title, x + 12, yTop - 22, 10, false, colorMuted);
      drawText(value, x + 12, yTop - 48, 16, true, colorText);
    };

    const profit = outputs.profit ?? 0;
    const marginVal = outputs.margin ?? 0;
    const beAds = outputs.breakEvenCPA ?? 0;
    const beReturn = outputs.breakEvenROAS ?? 0;

    const x1 = marginX;
    const x2 = marginX + boxW + gap;

    drawKpiBox(x1, y, t.profit, money(profit));
    drawKpiBox(x2, y, t.margin, pct(marginVal));

    y -= boxH + 12;

    drawKpiBox(x1, y, t.beAds, money(beAds));
    drawKpiBox(x2, y, t.beReturn, `${Number(beReturn || 0).toFixed(2)}x`);

    y -= boxH + 22;
    drawLine(y);
    y -= 22;

    // Inputs section (2 columns list)
    drawText(t.sectionInputs, marginX, y, 13, true);
    y -= 14;

    const rows = Array.isArray(inputs) ? inputs : [];

    const colGap = 24;
    const colW = (width - marginX * 2 - colGap) / 2;
    const col1X = marginX;
    const col2X = marginX + colW + colGap;

    const rowH = 16;
    const maxRowsPerCol = 14; // fits nicely

    const drawRow = (x, y, label, value) => {
      drawText(label, x, y, 10, false, colorMuted);
      drawText(value, x + 220, y, 10, true, colorText);
    };

    let i = 0;
    let yy1 = y;
    let yy2 = y;

    for (const r of rows) {
      const label = r?.label ?? "";
      const value = r?.value ?? "";
      const isCol1 = i < maxRowsPerCol;

      if (isCol1) {
        drawRow(col1X, yy1, label, value);
        yy1 -= rowH;
      } else {
        drawRow(col2X, yy2, label, value);
        yy2 -= rowH;
      }
      i += 1;
    }

    y = Math.min(yy1, yy2) - 10;

    y -= 10;
    drawLine(y);
    y -= 22;

    // Insight
    drawText(t.sectionNotes, marginX, y, 13, true);
    y -= 16;

    const insight = String(meta?.insight ?? "");
    const status = String(meta?.status ?? "");

    const badgeText = status ? status.toUpperCase() : "";
    if (badgeText) {
      page.drawRectangle({
        x: marginX,
        y: y - 18,
        width: 110,
        height: 20,
        color: rgb(0.93, 0.95, 1),
        borderColor: colorAccent,
        borderWidth: 1,
      });
      drawText(badgeText, marginX + 10, y - 14, 10, true, colorAccent);
    }

    y -= 34;

    // Simple wrapped paragraph
    const wrap = (text, maxChars = 92) => {
      const words = text.split(/\s+/);
      const lines = [];
      let line = "";
      for (const w of words) {
        const next = line ? `${line} ${w}` : w;
        if (next.length > maxChars) {
          if (line) lines.push(line);
          line = w;
        } else {
          line = next;
        }
      }
      if (line) lines.push(line);
      return lines;
    };

    const insightLines = wrap(insight || "");
    for (const ln of insightLines.slice(0, 7)) {
      drawText(ln, marginX, y, 11, false, colorText);
      y -= 16;
    }

    // Output PDF
    const pdfBytes = await pdfDoc.save();
    return new NextResponse(pdfBytes, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="real-ecommerce-profit-report.pdf"`,
        "Cache-Control": "no-store",
      },
    });
  } catch (err) {
    return NextResponse.json({ error: "Failed to generate PDF" }, { status: 500 });
  }
}
